export const pairs = [
  { id: 1, cs: '.', en: 'point' },
  { id: 2, cs: ',', en: 'comma' },
  { id: 3, cs: ';', en: 'semicolon' },
  { id: 4, cs: ':', en: 'colon' },
  { id: 5, cs: '" "', en: 'double quotes' },
  { id: 6, cs: '\' \'', en: 'single quotes' },
  { id: 7, cs: '` `', en: 'backquotes' },
  { id: 8, cs: '( )', en: 'round brackets' },
  { id: 9, cs: '[ ]', en: 'square brackets' },
  { id: 10, cs: '{ }', en: 'curly brackets' },
  { id: 11, cs: '< >', en: 'angle brackets' },
  { id: 12, cs: '|', en: 'pipe' },
  { id: 13, cs: '&', en: 'ampersand' },
  { id: 14, cs: '?', en: 'question mark' },
  { id: 15, cs: '!', en: 'exclamation point' },
  { id: 16, cs: '/', en: 'slash' },
  { id: 17, cs: '\\', en: 'backslash' },
  { id: 18, cs: '*', en: 'asterisk' },
  { id: 19, cs: '=', en: 'equals sign' },
  { id: 20, cs: '@', en: 'at sign' },
  { id: 21, cs: '#', en: 'hash' },
  { id: 22, cs: '~', en: 'tilde' },
  { id: 23, cs: '-', en: 'dash' },
  { id: 24, cs: '+', en: 'plus sign' },
  { id: 25, cs: 'hodnota', en: 'value' },
  { id: 26, cs: 'výraz', en: 'expression' },
  { id: 27, cs: 'řetězec', en: 'string' },
  { id: 28, cs: 'vstup', en: 'input' },
  { id: 29, cs: 'výstup', en: 'output' },
  { id: 30, cs: 'proměnná', en: 'variable' },
  { id: 31, cs: 'vlastnost', en: 'property' },
  { id: 32, cs: 'klíč', en: 'key' },
  { id: 33, cs: 'metoda', en: 'method' },
  { id: 34, cs: 'funkce', en: 'function' },
  { id: 35, cs: 'pravdivostní hodnota', en: 'boolean value' },
  { id: 36, cs: 'knihovna', en: 'library' },
  { id: 37, cs: 'obor platnosti', en: 'scope' },
  { id: 38, cs: 'zastínění', en: 'shadowing' },
  { id: 39, cs: 'událost', en: 'event' },
  { id: 40, cs: 'pole', en: 'array' },
  { id: 41, cs: 'řídící proměnná', en: 'control variable' },
  { id: 42, cs: 'rozhraní', en: 'interface' },
  { id: 43, cs: 'balíček', en: 'package' },
  { id: 44, cs: 'operátor pro podmíněný výraz', en: 'conditional operator' },
  { id: 45, cs: 'třída', en: 'class' },
  { id: 46, cs: 'stav', en: 'state' },
  { id: 47, cs: 'zalomení', en: 'wrap' },
  { id: 48, cs: 'hlavní osa', en: 'main axis' },
  { id: 49, cs: 'vedlejší osa', en: 'cross axis' },
  { id: 50, cs: 'potomek', en: 'descendant' },
  { id: 51, cs: 'sourozenec', en: 'sibling' },
  { id: 52, cs: 'rodič', en: 'parent' }
];